# Compose Docker container with sub-containers apache-php7 & mariadb
# Each sub-containers are described by their own Dockerfile
version: '3'
services:
  apache-php7:
    build: ./apache-php7
    ports:
      - '80:80'
      - '8000:8000'
    volumes:
      - ${DEV_PROJECT_PATH}:/var/www/html
      - ./apache-php7/sites-enabled:/etc/apache2/sites-enabled
  mariadb: 
    build: ./mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'