# Compose Docker container with sub-containers apache-php7 & mariadb
# Each sub-containers are described by their own Dockerfile
version: '3'
networks:
  men_default:
    external: true
services:
  apache-php7:
    build: ./apache-php7
    container_name: service-apache
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
    tty: true
    volumes:
      - ${DEV_PROJECT_PATH}:/var/www/html
      - ${DEV_VHOST_PATH}:/etc/apache2/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - DOMAINES=${SSL_HOST_DOMAINES}
    networks:
      - default
      - men_default
    external_links:
      - service-node
  mariadb:
    build: ./mariadb
    container_name: service-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: service-pma
    links:
      - mariadb:db
    restart: always
    ports:
      - '8080:80'
