# Compose Docker container with sub-containers apache-php7 & mariadb
# Each sub-containers are described by their own Dockerfile
version: '3'
networks:
  men_default:
    external: true
services:
  apache-php7:
    build: ./apache-php7
    container_name: i2r-dev-apache
    ports:
      - '80:80'
      - '8000:8000'
    volumes:
      - ${DEV_PROJECT_PATH}:/var/www/html
      - ./apache-php7/sites-enabled:/etc/apache2/sites-enabled
    networks:
      - default
      - men_default
    external_links:
      - i2r-dev-node
  mariadb:
    build: ./mariadb
    container_name: i2r-dev-mariadb
    environment:
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ${MYSQL_DATA_PATH}:/bitnami/mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: i2r-dev-pma
    links:
      - mariadb:db
    restart: always
    ports:
      - '8080:80'
