############################################################
# Build the container for MariaDB
############################################################

FROM mariadb:latest

MAINTAINER Quentin Tshaimanga
