############################################################
# Build the container for MariaDB
############################################################

FROM bitnami/mariadb:latest

MAINTAINER Quentin Tshaimanga
